defmodule AshStorage.TestRepo.Migrations.AddArgTestResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:with_args_parents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:arg1, :text)
      add(:stored_at, :utc_datetime_usec)
    end

    create table(:with_args_children, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:arg1, :text)

      add(
        :parent_id,
        references(:with_args_parents,
          column: :id,
          name: "with_args_children_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:stored_at, :utc_datetime_usec)
    end
  end

  def down do
    drop(constraint(:with_args_children, "with_args_children_parent_id_fkey"))

    drop(table(:with_args_children))

    drop(table(:with_args_parents))
  end
end
