# SPDX-FileCopyrightText: 2020 Zach Daniel
#
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    with:
      postgres: true
      postgres-version: "16"
      reuse: true
    secrets:
      hex_api_key: ${{ secrets.HEX_API_KEY }}
